---
- name: installation of apps, packaging and running
  hosts: web
  become: yes

  tasks:
  - name: ensure maven is installed
    apt:
       name: maven
       state: present

  - name: ensure tomcat is installed
    apt:
       name: tomcat8
       state: present

  - name: ensure git is installed
    apt:
       name: git
       state: present

  - name: ensure java is installed
    apt:
       name: default-jdk
       state: present

  - name: set JAVA_HOME
    shell: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

  - name: clone project from git
    git:
       repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
       dest: /home/project/

  - name: maven package
    command: mvn package -f /home/project

  - name: copy war file to webapps
    copy:
       remote_src: yes
       src: /home/project/target/hello-1.0.war
       dest: /var/lib/tomcat8/webapps
       force: yes
    notify:
       - tomcat8 restart

  handlers:
   - name: tomcat8 restart
     service: name=tomcat8 state=restart
